version: "3"
services:
  dummy-app-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - /app/node_modules
      - .:/app
  dummy-app-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
